version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  
jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli:
          run: aws sts get-caller-identity
